### PR TITLE
ie11 Bug which stop rendering slick-grid

### PR DESCRIPTION
**Pull request by pixelbyaj**
I have changed a code so it can work for IE11 and on Edge browser.

### CODE REVIEW

**Comment by anthonydresser** [comment]
It looks like they have made this fix in the parent fork. I'm going to see if it is feasible to do a merge, which would also fix this problem. If it isn't feasible we can merge this in.

**Comment by anthonydresser** [comment]
@joshiabk if you get a moment could you try the https://github.com/anthonydresser/SlickGrid/pull/5. I've done a merge from the 6pac repo.

**Comment by pixelbyaj** [comment]
The merge of 6pac repo is working in IE. I think the changes you did for shadow DOM was breaking on IE. If you want to add shadow the code of mine has included that part

**Comment by anthonydresser** [comment]
I've merged in the merge from 6pac repo. For now I don't see a compelling reason to keep the shadow DOM stuff. If we find a need for it in the future we can add it back in.

**Pull request closed without merging**
